{{- if .Values.secrets }}
{{ $root := . }}
  {{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $namespace := print $root.Values.tenant "-" $root.Values.environment }}{{ $namespace }}
  {{- if $root.Values.overrideName }}
  name: {{ $namespace }}-mongodb-queries-{{ lower $root.Values.overrideName }}-{{ $secret.name }}
  {{- else }}
  name: {{ $namespace }}-mongodb-queries-{{ include "replaceDotsWithDashes" $root.Values.mongodbCollection }}-{{ $secret.name }}
  {{- end }}
  labels:
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}"
    release: {{ $root.Release.Name }}
    {{- if $root.Values.labels }}{{ toYaml $root.Values.labels | nindent 4 }}{{ end }}
type: Opaque
data:
  {{- range $k, $v := $secret.values }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}

